version: '3'

services:
  reservation-front:
    container_name: reservation-front
    image: reservation-front:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3030:80